runfile('C:/Users/AA/GUI/window_geometry.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/window_labels.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/window_label_twobuttons.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/frame_widget.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/getting_started_1.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/canvas.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/window_label_twobuttons.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/window_labels.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/window_label_twobuttons.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/getting_started.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/frame_widget.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/canvas.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/window_geometry.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/window_labels.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/frame_widget.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/canvas.py', wdir='C:/Users/AA/GUI')
debugfile('C:/Users/AA/GUI/canvas.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/canvas.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/window_geometry.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/buttons_tkinter.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/frame_widget.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/Guessing_Game.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/tkinter_calculator.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/getting_started_1.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/tkinter_calculator.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/buttons_tkinter.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/getting_started_1.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/buttons_tkinter.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/stopwatch_GUI.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/Guessing_Game.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/buttons_tkinter.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/stopwatch_GUI.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/buttons_tkinter.py', wdir='C:/Users/AA/GUI')

##---(Sun Dec  3 19:32:52 2017)---
runfile('C:/Users/AA/GUI/stopwatch_GUI.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/stopwatch1_GUI.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/canvas.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/stopwatch1_GUI.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/stopwatch_GUI.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/stopwatch1_GUI.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/Username_Password.py', wdir='C:/Users/AA/GUI')

##---(Tue Dec  5 18:11:47 2017)---
runfile('C:/Users/AA/GUI/Username_Password.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/window_label_twobuttons.py', wdir='C:/Users/AA/GUI')

##---(Tue Dec  5 21:53:36 2017)---
runfile('C:/Users/AA/GUI/automotive_db.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/automative_db1.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/automotive_db.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/automative_db1.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/automotive_db.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/automative_db1.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/window_labels.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/buttons_tkinter.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/canvas.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/getting_started_1.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/getting_started.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/automative_db1.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/automotive_db.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/automative_db1.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/automotive_db.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/GUI/automative_db1.py', wdir='C:/Users/AA/GUI')
runfile('C:/Users/AA/Error_Handling/getting_started.py', wdir='C:/Users/AA/Error_Handling')
div(2/3)
runfile('C:/Users/AA/Error_Handling/getting_started.py', wdir='C:/Users/AA/Error_Handling')
div(2, 3)
div(2, 0)
runfile('C:/Users/AA/Error_Handling/some_error.py', wdir='C:/Users/AA/Error_Handling')

##---(Wed Dec  6 09:24:36 2017)---
runfile('C:/Users/AA/File_Handling/File_exe_1.py', wdir='C:/Users/AA/File_Handling')
runfile('C:/Users/AA/File_Handling/printing.py', wdir='C:/Users/AA/File_Handling')
runfile('C:/Users/AA/File_Handling/opening_a_file.py', wdir='C:/Users/AA/File_Handling')
fobj = open("C:\workspace\phone.txt")
fobj
fobj.close()
runfile('C:/Users/AA/File_Handling/read_file.py', wdir='C:/Users/AA/File_Handling')
fobj = open("C:\workspace\phone.txt")
fobj.read()
import pickle
example_dict = {1:"6",2:"2",3:"f"}
pickle_out = open("dict.pickle","wb")
pickle.dump(example_dict, pickle_out)
pickle_out.close()
runfile('C:/Users/AA/File_Handling/pickle.py', wdir='C:/Users/AA/File_Handling')
runfile('C:/Users/AA/File_Handling/phone_text.py', wdir='C:/Users/AA/File_Handling')
runfile('C:/Users/AA/File_Handling/pickle.py', wdir='C:/Users/AA/File_Handling')
runfile('C:/Users/AA/File_Handling/students.py', wdir='C:/Users/AA/File_Handling')
runfile('C:/Users/AA/File_Handling/phone_text.py', wdir='C:/Users/AA/File_Handling')
runfile('C:/Users/AA/File_Handling/pickle.py', wdir='C:/Users/AA/File_Handling')
runfile('C:/Users/AA/File_Handling/phone_text.py', wdir='C:/Users/AA/File_Handling')
runfile('C:/Users/AA/File_Handling/students.py', wdir='C:/Users/AA/File_Handling')
runfile('C:/Users/AA/File_Handling/phone_text.py', wdir='C:/Users/AA/File_Handling')
runfile('C:/Users/AA/File_Handling/students.py', wdir='C:/Users/AA/File_Handling')

##---(Tue Dec 12 18:28:24 2017)---
runfile('C:/Users/AA/File_Handling/File_exe_1.py', wdir='C:/Users/AA/File_Handling')

##---(Tue Dec 12 18:41:08 2017)---
runfile('C:/Users/AA/.spyder-py3/temp.py', wdir='C:/Users/AA/.spyder-py3')

##---(Tue Dec 12 18:56:58 2017)---
runfile('C:/Users/AA/.spyder-py3/temp.py', wdir='C:/Users/AA/.spyder-py3')
print(a + b)
print (a)
a = "hello world"
print(a)
runfile('C:/Users/AA/.spyder-py3/temp.py', wdir='C:/Users/AA/.spyder-py3')
runfile('C:/Users/AA/File_Handling/opening_a_file.py', wdir='C:/Users/AA/File_Handling')
runfile('C:/Users/AA/File_Handling/with_statement.py', wdir='C:/Users/AA/File_Handling')
runfile('C:/Users/AA/File_Handling/students.py', wdir='C:/Users/AA/File_Handling')
runfile('C:/Users/AA/File_Handling/students.py', wdir='C:/Users/AA/File_Handling')

##---(Tue Dec 12 22:22:18 2017)---
runfile('C:/Users/AA/File_Handling/File_exe_1.py', wdir='C:/Users/AA/File_Handling')
runfile('C:/Users/AA/File_Handling/File_exe_1.py', wdir='C:/Users/AA/File_Handling')